core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fetchdata.urls')),
    path('accounts/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fetchdata/urls.py
from django.urls import path
from . import views

app_name = "fetchdata"

urlpatterns = [
    path('', views.HomeView.as_view(), name="HomeView"),
    path('scraper/<slug:slug>/', views.ScraperView.as_view(), name="ScraperView"),
    path('scraper/<slug:slug>/<slug:scrap_opt>/', views.SheetDataView.as_view(), name="SheetDataView"),
    path('scraper_data/<slug:slug>/<slug:scrap_opt>/', views.ScraperDataView.as_view(), name="ScraperDataView"),
    path('telegram_number_add/', views.TelegramNumberView.as_view(), name="TelegramNumberView"),
    path('manage_sequence/', views.ManageSequenceView.as_view(), name="ManageSequenceView"),
    path('upload_data/', views.UploadDataView.as_view(), name="UploadDataView"),
    path('processed_files/', views.UserProcessedFileView.as_view(), name="UserProcessedFileView"),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='RegisterView'),
    path('profile/', views.ProfileView.as_view(), name='ProfileView'),
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'),
    path('settings/', views.SettingsView.as_view(), name='SettingsView'),
    path('settings1/', views.Settings1View.as_view(), name='Settings1View'),
]

templates/template-parts/footer.html
{% load static %}
<footer class="bg-light text-dark" style="overflow: hidden;">
  <!-- Footer -->
  <section id="footer">
    <div class="container">
      <div class="row text-xs-center text-sm-left text-md-left">
        <div class="col-xs-12 col-sm-4 col-md-4 pe-5">
          <ul class="list-unstyled">
            <li>
              <img
                width="200px"
                src="{% static 'images/logo.png' %}"
                class="attachment-full size-full mb-3"
                alt=""
                loading="lazy"
                style="filter: hue-rotate(75deg);"
              />
            </li>
            <li>
              <p class="text-muted">We’ll help you navigate today’s ever-changing business environment with teams of technical experts and decades of industry experience.</p>
            </li>
            <li>
              <div class="row">
                <div class="col-2">
                  <i class="fab fa-youtube" style="font-size: 30px;"></i>
                </div>
                <div class="col-2">
                  <i class="fab fa-instagram" style="font-size: 30px;"></i>
                </div>
                <div class="col-2">
                  <i class="fab fa-facebook" style="font-size: 30px;"></i>
                </div>
              </div>
            </li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4">
          <h5 class="text-primary">Services</h5>
          <ul class="list-unstyled quick-links">
            <li>
              <a href="#">Home</a>
            </li>
            <li>
              <a href="#">About</a>
            </li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4">
          <h5 class="text-primary">Resources</h5>
          <ul class="list-unstyled quick-links">
            <li>
              <a href="#">Scrapers</a>
            </li>
            <li>
              <a href="#">Sample</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <section class="row bg-primary py-3">
    <div class="col-6 text-light px-4">
      <strong>
        © Copyright Bulk Skips - All rights reserved
      </strong>
    </div>
    <div class="col-6">

    </div>
  </section>
</footer>

templates/template-parts/navbar.html
{% load static %}
<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="main-navbar">
  <div class="container">
    <a class="navbar-brand" href="{% url 'fetchdata:HomeView' %}">
      <img
        width="200px"
        src="{% static 'images/logo.png' %}"
        class="attachment-full size-full"
        alt=""
        loading="lazy"
        style="filter: hue-rotate(75deg);"
      />
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if not user.is_authenticated %}
          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'users:RegisterView' %}">Sign Up</a>
          </li>
        {% else %}
          {% comment %} <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'fetchdata:UploadDataView' %}">Data Upload</a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'fetchdata:UserProcessedFileView' %}">My Processed Files</a>
          </li> {% endcomment %}
          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'users:ProfileView' %}">Profile</a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-link" href="{% url 'users:logout' %}">LogOut</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- Navbar End -->