core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fetchdata.urls')),
    path('accounts/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fetchdata/urls.py
from django.urls import path
from . import views

app_name = "fetchdata"

urlpatterns = [
    path('', views.HomeView.as_view(), name="HomeView"),
    path('scraper/<slug:slug>/', views.ScraperView.as_view(), name="ScraperView"),
    path('scraper/<slug:slug>/<slug:scrap_opt>/', views.SheetDataView.as_view(), name="SheetDataView"),
    path('scraper_data/<slug:slug>/<slug:scrap_opt>/', views.ScraperDataView.as_view(), name="ScraperDataView"),
    path('telegram_number_add/', views.TelegramNumberView.as_view(), name="TelegramNumberView"),
    path('manage_sequence/', views.ManageSequenceView.as_view(), name="ManageSequenceView"),
    path('upload_data/', views.UploadDataView.as_view(), name="UploadDataView"),
    path('processed_files/', views.UserProcessedFileView.as_view(), name="UserProcessedFileView"),
]

fetchdata/models.py
import os
from urllib.parse import urlparse
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ScraperData(models.Model):
    SCRAPER_NAMES = (
        ('T', 'Telegram'),
        ('R', 'Reddit'),
    )

    scraper_name = models.CharField(max_length=255, choices=SCRAPER_NAMES)
    cryptocurrency = models.CharField(max_length=255)
    ticker = models.CharField(max_length=50)
    yesterday_total = models.IntegerField(default=0, null=True)
    today_total = models.IntegerField(default=0, null=True)
    difference = models.IntegerField(default=0, null=True)
    yesterday_icospeaks = models.IntegerField(default=0, null=True)
    today_icospeaks = models.IntegerField(default=0, null=True)
    yesterday_cryptocom = models.IntegerField(default=0, null=True)
    today_cryptocom = models.IntegerField(default=0, null=True)
    yesterday_coinmarket = models.IntegerField(default=0, null=True)
    today_coinmarket = models.IntegerField(default=0, null=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=False, null=True)

class OutputFileUpload(models.Model):
    file = models.FileField(upload_to='documents/output_files/%Y/%m/%d/')
    date_created = models.DateTimeField(auto_now_add=True)

class InputFileUpload(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="files_uploaded")
    input_file = models.FileField(upload_to='documents/input_files/%Y/%m/%d/')
    output_file = models.ForeignKey(OutputFileUpload, on_delete=models.CASCADE, related_name="input_files")
    date_created = models.DateTimeField(auto_now_add=True)

    @staticmethod
    def get_file_by_output(output_ins):
        return InputFileUpload.objects.filter(output_file = output_ins).first()

class ProcessedFile(models.Model):
    input_file = models.OneToOneField(InputFileUpload, on_delete=models.CASCADE, related_name="processed_file")
    processed_file = models.FileField(upload_to='documents/processed/%Y/%m/%d/')
    date_created = models.DateTimeField(auto_now_add=True)

    @staticmethod
    def get_files_by_user(user):
        return ProcessedFile.objects.filter(input_file__user = user)

    @property
    def get_name(self):
        return os.path.basename(self.processed_file.url)

    @property
    def get_input_name(self):
        return os.path.basename(self.input_file.input_file.url)

templates/core/data_upload.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block ExtraCss %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;700&display=swap" rel="stylesheet">


<style>
    .gray-bg{
        background:#eee;    
    }
    .pageloader {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      z-index: 1000000;
      opacity:1;
      overflow: hidden;
      display: table;
      padding: 50px;
      /* border: 2px var(--seconary-color) solid; */
      border-radius: 10px;
    }
    .loader {
      text-align: center;
      display: table-cell;
      vertical-align: middle;
    }
    .loader span{
      color: var(--secondary-color);
      {% comment %} display: block;
      margin-top: 40px; {% endcomment %}
    }
    .sp-hydrogen {
      width: 96px;
      height: 96px;
      clear: both;
      margin: 60px auto;
      position: relative;
      border: 3px var(--secondary-color) solid;
      border-radius: 50%;
      -webkit-animation: spHydro 0.7s infinite linear;
      animation: spHydro 0.7s infinite linear;
    }
    .sp-hydrogen:before, .sp-hydrogen:after {
      content: '';
      position: absolute;
      width: 30px;
      height: 30px;
      background-color: #252830;
      border-radius: 50%;
    }
    .sp-hydrogen:before {
      top: calc( 50% - 15px );
      left: calc( 50% - 15px );
    }
    .sp-hydrogen:after {
      top: -3px;
      left: -3px;
    }
    
    @-webkit-keyframes spHydro {
      from {
        -webkit-transform: rotate(0deg);
      }
      to {
        -webkit-transform: rotate(359deg);
      }
    }
    @keyframes spHydro {
      from {
        transform: rotate(0deg);
      }
      to {
        transform: rotate(359deg);
      }
    }
    
    
    
      .animated {
        -webkit-animation-duration: 1s;
        animation-duration: 1s;
        -webkit-animation-fill-mode: both;
        animation-fill-mode: both;
      }
    
      .animated.infinite {
        -webkit-animation-iteration-count: infinite;
        animation-iteration-count: infinite;
      }
    
      @-webkit-keyframes fadeIn {
        0% {
          opacity: 0;
        }
    
        100% {
          opacity: 1;
        }
      }
    
      @keyframes fadeIn {
        0% {
          opacity: 0;
        }
    
        100% {
          opacity: 1;
        }
      }
    
      .fadeIn {
        -webkit-animation-name: fadeIn;
        animation-name: fadeIn;
      }
    
      @-webkit-keyframes fadeOut {
        0% {
          opacity: 1;
        }
    
        100% {
          opacity: 0;
        }
      }
    
      @keyframes fadeOut {
        0% {
          opacity: 1;
        }
    
        100% {
          opacity: 0;
        }
      }
    
      .fadeOut {
        -webkit-animation-name: fadeOut;
        animation-name: fadeOut;
      }
    
</style>
{% endblock ExtraCss %}

{% block content %}

{% block header %}
{% endblock header %}

<div class="container my-5">
    <div class="row">
        <div class="col-lg-12 card-margin">
            <div class="card p-5 mx-auto">
                <h2 style="color: var(--temp-primary);" class="fs-1">Custom Data Scrap</h2>
                <form action="{% url 'fetchdata:UploadDataView' %}" method="POST" id="file-form" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-6">
                            <div class="mb-3">
                                <label for="inputFormFiles" class="form-label">Upload Input Files</label>
                                <input class="form-control" type="file" id="inputFormFiles" name="input_files" multiple required>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="mb-3">
                                <label for="outputFormFiles" class="form-label">Upload Output Format</label>
                                <input class="form-control" type="file" id="outputFormFiles" name="output_file" required>
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-success mt-4" type="submit">Upload</button>
                    <a href="{% url 'fetchdata:UserProcessedFileView' %}" class="btn btn-primary mt-4">View Processed Files</a>
                    {% comment %} <button class="btn btn-success mt-4" onclick="handleLoading('Please Wait...')" type="button">Upload</button> {% endcomment %}
                </form>
            </div>
        </div>

        <div class="col-lg-12 card-margin mt-4 form-file-text-body hidden" id="uploaded-files-cont">
            <div class="card p-5 mx-auto form-file-text">
                <h2 style="color: var(--temp-primary);" class="fs-1 text-center mb-4">Uploaded Files</h2>

                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Name</th>
                      <th scope="col">Size</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
                <button class="btn btn-warning mt-4 hidden" type="button" id="process-btn">Process Files</button>
            </div>
        </div>
    </div>

    <div class="pageloader bg-light shadow hidden" id="scraper-loader">
        <div class="loader">
          <span class="display-4">Scraping Data...</span>
          <div class="sp-hydrogen"></div>
        </div>
    </div>
    <div class="pageloader bg-light shadow hidden" id="generic-loader">
        <div class="loader">
          <span class="display-4 text-msg"></span>
          <div class="sp-hydrogen"></div>
        </div>
    </div>
</div>

<div id="message-area" class="hidden">
  <p id="text-content" class="fs-6 lead">Notification</p>
</div>
{% endblock content %}

{% block ExtraJs %}

<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>



<script>
    function showUploadedFiles() {
      $('#uploaded-files-cont')[0].classList.toggle("hidden", false);
      var files = $('#inputFormFiles')[0].files;
      let tableBody = $('.form-file-text-body').find(".table tbody")
      
      for (let i = 0; i < files.length; i++) {
        let file = files[i];
        let tableRows = $('.form-file-text-body').find(".table tbody tr")
        tableBody.html(
          tableBody.html() + `
          <tr>
            <th>${tableRows.length+1}</th>
            <td>${file.name}</td>
            <td>${file.size/1000} kB</td>
          </tr>
        `)
      }
    };

    const fileForm = document.getElementById("file-form");
    const processBtn = document.getElementById("process-btn");
  
    $("#file-form").submit(function(e) {
      e.preventDefault();
      var formData = new FormData(this);

      handleLoading("Uploading Files", status=true)

      $.ajax({
          url: window.location.pathname,
          type: 'POST',
          data: formData,
          success: function (res, textStatus, xhr) {
            handleLoading("", status=false)
            if (xhr.status == 200){
              processBtn.classList.toggle('hidden', false)
              showUploadedFiles()
              {% comment %} window.location.href = "{% url 'fetchdata:UserProcessedFileView' %}" {% endcomment %}

            }
          },
          error: function (res, textStatus, xhr) {
            handleLoading("", status=false)
          },
          cache: false,
          contentType: false,
          processData: false
        });
    });

    processBtn.addEventListener("click", ()=>{
      handleLoading("Processing Files", status=true)
      setTimeout(() => {
        window.location.href = "{% url 'fetchdata:UserProcessedFileView' %}"
      }, 4000);
    })

</script>


<script>
  function closeParent(elem) {
    elem.parentElement.classList.toggle("show", false);
    elem.parentElement.classList.toggle("hidden", true);
  }
  function openElem(class_name) {
    document.querySelector(class_name).classList.toggle("show", true);
    document.querySelector(class_name).classList.toggle("hidden", false);
  }

  let to = null;
  function popUp(msg) {
    if (to) {
      clearTimeout(to);
    }
    const message_area = document.getElementById("message-area");
    message_area.classList.toggle("hidden", true);
    message_area.querySelector("#text-content").innerText = msg;
    setTimeout(() => {
      message_area.classList.toggle("hidden", false);
    }, 200);
    to = setTimeout(() => {
      message_area.classList.toggle("hidden", true);
    }, 2000);
  }
</script>

<script>
    const scraperLoader = document.getElementById("scraper-loader")
    function handleSrap(elem){

        setTimeout(() => {
            scraperLoader.classList.toggle("hidden", false);
        }, 200);

        to = setTimeout(() => {
            scraperLoader.classList.toggle("hidden", true);
        }, 3000);
    }

    const loader = document.getElementById("generic-loader")
    function handleLoading(text, status=false){
      loader.getElementsByClassName("text-msg")[0].innerText = text
      loader.classList.toggle("hidden", !status);

      {% comment %} to = setTimeout(() => {
          loader.classList.toggle("hidden", true);
      }, 3000); {% endcomment %}
    }
</script>

{% endblock ExtraJs %}

templates/core/my_processed_files.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block ExtraCss %}
  {% comment %} <style>
    * {
      box-sizing: border-box;
    }

    #myInput {
      background-image: url('/css/searchicon.png');
      background-position: 10px 10px;
      background-repeat: no-repeat;
      width: 100%;
      font-size: 16px;
      padding: 12px 20px 12px 40px;
      border: 1px solid #ddd;
      margin-bottom: 12px;
    }

    #myTable {
      border-collapse: collapse;
      width: 100%;
      border: 1px solid #ddd;
      font-size: 18px;
    }

    #myTable th, #myTable td {
      text-align: left;
      padding: 12px;
    }

    #myTable tr {
      border-bottom: 1px solid #ddd;
    }

    #myTable tr.header, #myTable tr:hover {
      background-color: #f1f1f1;
    }
  </style> {% endcomment %}
{% endblock ExtraCss %}

{% block content %}

{% block header %}
{% endblock header %}

<section class="container my-5">

    <div class="row">
        <div class="col-12" style="overflow-x: auto;">

          <table class="table table-stripped" id="table">
            <thead>
                <tr class="header">
                  <th>FileName</th>
                  <th>Date Processed</th>
                  <th>Download</th>
                </tr>
            </thead>
            <tbody>
                {% for file in processed_files %}
                <tr> 
                  <td>{{file.get_input_name}}</td>
                  <td>{{file.date_created}}</td>
                  <td>
                    <form action="." method="POST">
                      {% csrf_token %}
                      <input type="hidden" name="path" value="{{file.processed_file.url}}">
                      <button class="btn btn-warning btn-sm" type="submit">Download</button>
                    </form>
                  </td>
                </tr>
                {% endfor %}
            </tbody>
          </table>

        </div>
    </div>
</section>

{% endblock content %}

{% block ExtraJs %}


{% endblock ExtraJs %}

templates/core/scraper_detail.html
{% extends 'base.html' %}
{% load static %}

{% block ExtraCss %}

{% endblock ExtraCss %}

{% block content %}

{% block header %}
{% endblock header %}

<section class="container home-sect mb-5">
    <div class="text-center template-title mb-5">
        {% comment %} <h4><span>Select Service</span></h4> {% endcomment %}
        <h2>Select Service</h2>
    </div>

    <div class="row w-75 justify-content-center">
        {% comment %} <div class="col-6 col-md-4 text-center mb-3">
            <a href="{% url 'fetchdata:SheetDataView' slug=scraper_name scrap_opt='msg_scrap' %}" class="a-no-style card p-4" style="min-height: 0px;">
                <i class="far fa-envelope mb-3 text-secondary" style="font-size: 72px;"></i>
                <h2 class="lead">Message Scraping BOT</h2>
            </a>
        </div>
        <div class="col-6 col-md-4 text-center mb-3">
            <a href="{% url 'fetchdata:SheetDataView' slug=scraper_name scrap_opt='msg_send' %}" class="a-no-style card p-4" style="min-height: 0px;">
                <i class="fas fa-mail-bulk mb-3 text-secondary" style="font-size: 72px;"></i>
                <h2 class="lead">Message Sending BOT</h2>
            </a>
        </div>
        <div class="col-6 col-md-4 text-center mb-3">
            <a href="{% url 'fetchdata:SheetDataView' slug=scraper_name scrap_opt='auto_notify' %}" class="a-no-style card p-4" style="min-height: 0px;">
                <i class="far fa-bell mb-3 text-secondary" style="font-size: 72px;"></i>
                <h2 class="lead">Auto Notifying BOT</h2>
            </a>
        </div>
        <div class="col-6 col-md-4 text-center mb-3">
            <a href="{% url 'fetchdata:SheetDataView' slug=scraper_name scrap_opt='airdrop' %}" class="a-no-style card p-4" style="min-height: 0px;">
                <i class="fab fa-telegram mb-3 text-secondary" style="font-size: 72px;"></i>
                <h2 class="lead">Airdrop BOT</h2>
            </a>
        </div>
        <div class="col-6 col-md-4 text-center mb-3">
            <a href="{% url 'fetchdata:SheetDataView' slug=scraper_name scrap_opt='mem_scrap' %}" class="a-no-style card p-4" style="min-height: 0px;">
                <i class="fas fa-users-cog mb-3 text-secondary" style="font-size: 72px;"></i>
                <h2 class="lead">Members Scraping BOT</h2>
            </a>
        </div>
        <div class="col-6 col-md-4 text-center mb-3">
            <a href="{% url 'fetchdata:SheetDataView' slug=scraper_name scrap_opt='ques_ans' %}" class="a-no-style card p-4" style="min-height: 0px;">
                <i class="far fa-question-circle mb-3 text-secondary" style="font-size: 72px;"></i>
                <h2 class="lead">Question Answer BOT</h2>
            </a>
        </div>
        <div class="col-6 col-md-4 text-center mb-3">
            <a href="{% url 'fetchdata:SheetDataView' slug=scraper_name scrap_opt='add_remove' %}" class="a-no-style card p-4" style="min-height: 0px;">
                <i class="fas fa-user-times mb-3 text-secondary" style="font-size: 72px;"></i>
                <h2 class="lead">Auto Adder/Remover</h2>
            </a>
        </div> {% endcomment %}
        <div class="col-6 col-md-4 text-center mb-3">
            <a href="{% url 'fetchdata:SheetDataView' slug=scraper_name scrap_opt='custom_bot' %}" class="a-no-style card p-4" style="min-height: 0px;">
                <img src="{% static 'images/pdf-icon.jpg' %}" alt="PDF Icon" width="72px" class="m-auto mb-3">
                {% comment %} <i class="fas fa-cogs mb-3 text-secondary" style="font-size: 72px;"></i> {% endcomment %}
                <h2 class="lead">PDF Generator</h2>
            </a>
        </div>
    </div>
</section>

{% endblock content %}

{% block ExtraJs %}



{% endblock ExtraJs %}

templates/core/tebular_data.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block ExtraCss %}
  {% comment %} <style>
    * {
      box-sizing: border-box;
    }

    #myInput {
      background-image: url('/css/searchicon.png');
      background-position: 10px 10px;
      background-repeat: no-repeat;
      width: 100%;
      font-size: 16px;
      padding: 12px 20px 12px 40px;
      border: 1px solid #ddd;
      margin-bottom: 12px;
    }

    #myTable {
      border-collapse: collapse;
      width: 100%;
      border: 1px solid #ddd;
      font-size: 18px;
    }

    #myTable th, #myTable td {
      text-align: left;
      padding: 12px;
    }

    #myTable tr {
      border-bottom: 1px solid #ddd;
    }

    #myTable tr.header, #myTable tr:hover {
      background-color: #f1f1f1;
    }
  </style> {% endcomment %}
{% endblock ExtraCss %}

{% block content %}

{% block header %}
{% endblock header %}

<section class="container my-5">

    <div class="row mb-3">
        <div class="col-12">
            <form method="GET">
              {% comment %} cryptocurrency
              ticker
              order_by {% endcomment %}
              <div class="row align-items-end">
                <div class="col-4">
                  <div id="div_crypto_currency" class="form-group">
                      <label for="crypto_currency">Crypto Currency</label>
                      <div>
                          <input type="text" name="crypto_currency" class="textinput textInput form-control" id="id_cryptocurrency">
                      </div>
                  </div>
                </div>
                <div class="col-4">
                  <div id="div_ticker" class="form-group">
                      <label for="ticker">Ticker</label>
                      <div>
                          <input type="text" name="ticker" class="textinput textInput form-control" id="id_ticker">
                      </div>
                  </div>
                </div>
                {% comment %} <div class="col-4 text-center">
                  <div id="div_{{filter_form.form.order_by.id_for_label}}" class="form-group">
                      <label for="{{filter_form.form.order_by.id_for_label}}">{{filter_form.form.order_by.label}}</label>
                      <div>
                          {{filter_form.form.order_by}}
                      </div>
                  </div>
                </div> {% endcomment %}
                <div class="col-4 text-start">
                  <button class="btn btn-primary" type="submit">Filter</button>
                </div>
              </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12" style="overflow-x: auto;">

          <table class="table table-stripped" id="table">
            <thead>
                <tr class="header">
                    <th style="min-width: 100px;">Cryptocurrency</th>
                    <th style="min-width: 100px;">Ticker</th>
                    <th style="min-width: 100px;" onclick="sortTable(2)" data-direction="asc">Yesterday Total</th>
                    <th style="min-width: 100px;" onclick="sortTable(3)" data-direction="asc">Today Total</th>
                    <th style="min-width: 100px;" onclick="sortTable(4)" data-direction="asc">Difference</th>
                    <th style="min-width: 100px;" onclick="sortTable(5)" data-direction="asc">Yesterday Icospeaks</th>
                    <th style="min-width: 100px;" onclick="sortTable(6)" data-direction="asc">Today Icospeaks</th>
                    <th style="min-width: 100px;" onclick="sortTable(7)" data-direction="asc">Yesterday Cryptocom</th>
                    <th style="min-width: 100px;" onclick="sortTable(8)" data-direction="asc">Today Cryptocom</th>
                    <th style="min-width: 100px;" onclick="sortTable(9)" data-direction="asc">Yesterday Coinmarket</th>
                    <th style="min-width: 100px;" onclick="sortTable(10)" data-direction="asc">Today Coinmarket</th>
                    <th style="min-width: 130px;">Date</th>
                </tr>
            </thead>
            <tbody>
                {% for entry in data %}
                <tr> 
                    <td>{{entry.cryptocurrency}}</td>
                    <td>{{entry.ticker}}</td>
                    <td>{{entry.yesterday_total}}</td>
                    <td>{{entry.today_total}}</td>
                    <td>{{entry.difference}}</td>
                    <td>{{entry.yesterday_icospeaks}}</td>
                    <td>{{entry.today_icospeaks}}</td>
                    <td>{{entry.yesterday_cryptocom}}</td>
                    <td>{{entry.today_cryptocom}}</td>
                    <td>{{entry.yesterday_coinmarket}}</td>
                    <td>{{entry.today_coinmarket}}</td>
                    <td>{{entry.date.date}}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>

        </div>
        <div class="col-12">
          <div class="pagination">
            <span class="step-links">
                {% if data.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ data.previous_page_number }}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ data.number }} of {{ data.paginator.num_pages }}.
                </span>
        
                {% if data.has_next %}
                    <a href="?page={{ data.next_page_number }}">next</a>
                    <a href="?page={{ data.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
          </div>
        </div>
    </div>
</section>

{% endblock content %}

{% block ExtraJs %}

<script>
  function handleSorting(elem){
    console.log(elem)
    
  }
</script>


<script>
  function sortTable(n) {
      var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
      table = document.getElementById("table");
      switching = true;
      // Set the sorting direction to ascending:
      dir = table.rows[0].getElementsByTagName("TH")[n].getAttribute("data-direction")
      nextDir = dir == "asc" ? "desc" : "asc"
      //dir = "asc";
      /* Make a loop that will continue until
      no switching has been done: */
      while (switching) {
        // Start by saying: no switching is done:
        switching = false;
        rows = table.rows;
        //.getAttribute("data-direction");
        /* Loop through all table rows (except the
        first, which contains table headers): */
        for (i = 1; i < (rows.length - 1); i++) {
          // Start by saying there should be no switching:
          shouldSwitch = false;
          /* Get the two elements you want to compare,
          one from current row and one from the next: */
          x = rows[i].getElementsByTagName("TD")[n];
          y = rows[i + 1].getElementsByTagName("TD")[n];
          /* Check if the two rows should switch place,
          based on the direction, asc or desc: */
          if (dir == "asc") {
            if (Number(x.innerHTML) > Number(y.innerHTML)) {
              shouldSwitch = true;
              break;
            }
            {% comment %}
            if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
              // If so, mark as a switch and break the loop:
              shouldSwitch = true;
              break;
            }
            {% endcomment %}
          } else if (dir == "desc") {
            if (Number(x.innerHTML) < Number(y.innerHTML)) {
              shouldSwitch = true;
              break;
            }
          }
        }
        if (shouldSwitch) {
          /* If a switch has been marked, make the switch
          and mark that a switch has been done: */
          rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
          switching = true;
          // Each time a switch is done, increase this count by 1:
          switchcount ++;
        } else {
          /* If no switching has been done AND the direction is "asc",
          set the direction to "desc" and run the while loop again. */
          if (switchcount == 0 && dir == "asc") {
            dir = "desc";
            switching = true;
          }
        }
      }
      table.rows[0].getElementsByTagName("TH")[n].setAttribute("data-direction", nextDir)
  }
</script>

{% endblock ExtraJs %}